package com.roche.SchoolRegister.SchoolRegister.constants;

public enum MessageConstant {

    MESSAGE,
    GOTO,
    STUDENT,
    STUDENTS,
    TEACHER,
    TEACHERS,
    COURSE,
    COURSE_WITH_TEACHER,
    CAREER,
    ADMIN,
    LEVEL,
    ENTITIES,
    STUDENT_SUCCESS,
    TEACHER_SUCCESS,
    COURSE_SUCCESS,
    ADMIN_SUCCESS,
    CAREER_SUCCESS,
    ERROR_INSERTION_STUDENT,
    ERROR_INSERTION_TEACHER,
    ERROR_INSERTION_COURSE,
    ERROR_INSERTION_ADMIN,
    ERROR_INSERTION_CAREER,
    ERROR_PERSIST_ENTITY,
    ENTITY_INSERTED,
    ERROR_UPDATING_ENTITY,
    DELETED_SUCCESS,
    UPDATED_SUCCESS,
    INVALID_VALUE,
    INVALID_ID,
    USER_DELETED,
    ENTITY_DELETED,
    ERROR_DELETED_ENTITY,
    PARAMETER_ENTITY_NOT_VALID,
    ENTITY_UPDATED_SUCCESSFULLY,
    ID_DOES_NOT_EXIST,
    DNA_MAY_NOT_EXIST,
    ERROR_FILTERING_ENTITY,
    EMPTY_PARAMS,
    FOUNDED,
    ERROR,
    OVER_AMOUNT


}

